# Generated by Django 5.2.1 on 2025-08-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofa', '0002_nicolas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nicolas',
        ),
    ]
